/**
 * Copyright © 2014, 2015 Typesafe, Inc. All rights reserved. [http://www.typesafe.com]
 */

//TODO: This should be refactored in the same was as in the output repos generated by 'studentify'

import scala.Console

shellPrompt in ThisBuild := { state =>
  val base: File = Project.extract(state).get(sourceDirectory)
  val basePath: String = base + "/test/resources/README.md"
  val exercise = Console.BLUE + IO.readLines(new sbt.File(basePath)).head + Console.RESET
  val manRmnd = Console.RED + "man [e]" + Console.RESET
  val prjNbrNme = IO.readLines(new sbt.File(new sbt.File(Project.extract(state).structure.root), ".courseName")).head
  s"$manRmnd > $prjNbrNme > $exercise > "
}
